### ISSUE TITLE
Building for MSM8960/mako - no lkboot.img created

### ISSUE THREAD

**Issue by voltagex** [grub4android/lk#10]
I'm trying to port to the Nexus 4.

I've copied the msm8960-aries target folder and changed the lk target to msm8960. Unfortunately no lkboot.img file is created.

Any hints?

**Comment by M1cha** [comment]
aries builds native bootloader images because it has board security disabled.
check this out: https://github.com/grub4android/build/blob/master/devices/condor/device.mk
