### ISSUE TITLE
Xiaomi Redmi 1S and Note 4G vibrator not works

### ISSUE THREAD

**Issue by balika011** [grub4android/lk#7]
For 1S you have to set gpio 33 and 50 to high.
On Note 4G you need gpio 33 and 51.

**Comment by M1cha** [comment]
the vibrator should be enabled via pmic.
https://github.com/grub4android/lk/blob/master/dev/pmic/pm8x41/pm8x41_vib.c

Ofc you can do that via GPIO's but it may be a bad idea and could damage the vibrator.

**Comment by balika011** [comment]
Its controlled by an isa1000. These are the gpios for that.

**Comment by M1cha** [comment]
ISA1200 is a i2c device. You shouldn't use the gpio's directly their either.
I already tried to port the driver but LK still lacks support for GPIO interrupts. This is the requirement for all I2C devices(touchscreen, vibrator, ...).

I'll definitely look into that in future but atm it has no priority.

**Comment by M1cha** [comment]
closed because it's not directly related to G4A
