### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by voltagex** [grub4android/lk#8]
I'm just wondering if this fork of LK needs to be patched against https://www.codeaurora.org/projects/security-advisories/lk-improper-partition-bounds-checking-when-flashing-sparse-images-cve

**Comment by M1cha** [comment]
do you have some IM(IRC, Hangouts, Skype,...) where we can talk about some g4a related stuff?

**Comment by voltagex** [comment]
Hangouts - voltagex at voltagex dot org. I'm on Freenode as voltagex but I
can't reply as much.
